config/routes.rb
Bucms::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users
  resources :posts, path: "" do
    resources :comments
  end
  get 'tags/:tag', to: 'posts#index', as: :tag

  root 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == "admin"
      can :manage, :all
    elsif user.role == "reader"
      can :read, :all
      can :create, Comment
      can :delete, Comment do |comment|
        comment.try(:user) == user
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :post_id, :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :slug, uniqueness: true, presence: true

  before_validation :generate_slug

  belongs_to :user
  has_many :comments, :dependent => :destroy
  acts_as_taggable


  def to_param
    slug
  end

  def generate_slug
    self.slug ||= title.parameterize
  end
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :add_role

  validates :name, :email, uniqueness: true, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy

  def add_role
  	self.role = "reader"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_comments
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url
  end

  private

    def set_comments
      @comments = Comment.last(5)
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]
  before_action :set_comment, only: [:destroy]
  load_and_authorize_resource only: [:destroy]
  skip_load_resource only: [:create]

	def create
    @post = Post.find_by_slug!(params[:post_id])
    comment = @post.comments.build(comment_params)
    comment.user = current_user
 
    if comment.save
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
    end
  end

  def destroy
    @post = @comment.post
    @comment.delete
    redirect_to post_path(@post)
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource only: [:new, :edit, :create, :update, :destroy]
  skip_load_resource only: [:create]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 10, order: "created_at DESC")
    else
      @posts = Post.paginate(:page => params[:page], :per_page => 10, order: "created_at DESC")
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render action: 'edit'
    end
  end

  def show
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_slug!(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.slim
= form_for [@post, @post.comments.new] do |f|
  = f.text_area :body, class: 'form-control'
  br
  = f.submit "Добавить комментарий", class: 'btn btn-primary btn-sm'

app/views/comments/_index.html.slim
- @post.comments.each do |comment|
  p.col-md-12
    .col-md-2
      = image_tag avatar_url(comment.user)
    .container-fluid
      p
        b 
          - if comment.user.present?
            = comment.user.name
      p = comment.body
  p.col-md-12
    - if can? :delete, Comment 
      = link_to "Удалить комментарий", post_comment_path(@post, comment), method: :delete, class: 'btn btn-danger btn-xs'

app/views/layouts/application.html.slim
doctype
html
  head
    title
      - if @post == true
        = @post.title + ' | '
      | Own Paradigm - блог о программировании, играх и технических новинках
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    - if @post.present?
      meta content="#{truncate(@post.content, length: 460, :omission => "..." , :escape => false)}" name="description"
      meta content="#{@post.tag_list.to_s}" name="keywords"


body
  .navbar.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        = link_to " Own Paradigm", root_path, class: "navbar-brand"
        button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main"
          span.icon-bar
          span.icon-bar
          span.icon-bar
      .navbar-collapse.collapse#navbar-main
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li= link_to "Учетная запись", edit_user_registration_path
            li= link_to "Выйти", destroy_user_session_path
          - else
            li= link_to "Регистрация", new_user_registration_path
            li= link_to "Войти", new_user_session_path
  .container.main
    .col-lg-8.post
      = yield
    .col-lg-4
      .panel.panel-primary
        .panel-heading 
          h3.panel-title Облако тегов
        .panel-body
          - tag_cloud(Post.tag_counts, %w(css1 css2 css3 css4)) do |tag, css_class|
            = link_to tag.name, tag_path(tag.name), class: css_class
      .panel.panel-primary
        .panel-heading 
          h3.panel-title Последние комментарии
        .panel-body
          - @comments.each do |comment|
            p 
              b = comment.user.name
              | : 
              = link_to truncate(comment.body, length: 50), comment.post
footer.container
  .col-lg-12
    | Copyright © Own Paradigm 
    = DateTime.now.year 
  .col-lg-12
    <!--LiveInternet counter--><script type="text/javascript">document.write("<a href='http://www.liveinternet.ru/click' target=_blank><img src='//counter.yadro.ru/hit?t17.6;r" + escape(document.referrer) + ((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth)) + ";u" + escape(document.URL) + ";" + Math.random() + "' border=0 width=88 height=31 alt='' title='LiveInternet: показано число просмотров за 24 часа, посетителей за 24 часа и за сегодня'><\/a>")</script><!--/LiveInternet-->

app/views/posts/_form.html.slim
= form_for(@post) do |f|
  .form-group
    label
      = f.label "Заголовок статьи", class: 'control-label'
    = f.text_field :title, class: 'form-control'
  .form-group
    label
      = f.label "Текст статьи", class: 'control-label'
    = f.text_area :content, class: 'redactor'
  .form-group
    label
      = f.label "Теги(разделять запятыми)", class: 'control-label'
    = f.text_field :tag_list, class: 'form-control'
  .actions
    = f.submit "Подтвердить", class: 'btn btn-success'

app/views/posts/edit.html.slim
= render "form"

app/views/posts/index.html.slim
- if can? :create, Post
  p = link_to "Создать пост", new_post_path, class: 'btn btn-default btn-lg btn-block'
- @posts.each do |post|
  h3 = link_to post.title, post
  .label.label-info = post.created_at.strftime "%d/%m/%Y"
  p = truncate(post.content.html_safe, length: 460, :omission => "..." , :escape => false)
  p = link_to "Читать далее...", post, class: 'label label-info'
  .glyphicon.glyphicon-comment Комменатриев(#{post.comments.count})
  p
    .glyphicon.glyphicon-tag Теги:
    = post.tag_list.map { |t| link_to t, tag_path(t), class: 'label label-default' }.join(" ").html_safe
= will_paginate @posts, previous_label: "<<", next_label: ">>", class: "pagination"

app/views/posts/new.html.slim
= render "form"

app/views/posts/show.html.slim
h1 = @post.title
p = @post.content.html_safe
p 
  .glyphicon.glyphicon-tag Теги:
  = @post.tag_list.map { |t| link_to t, tag_path(t), class: 'label label-default' }.join(' ').html_safe
p
  .glyphicon.glyphicon-comment Комменатриев(#{@post.comments.count})
  = link_to "Поделиться VK", "http://vk.com/share.php?url=" + post_url, class: "label label-info"
- if can? :manage, Post
  p 
    = link_to "Редактировать", edit_post_path(@post), class: 'btn btn-warning btn-xs'
    = link_to "Удалить", @post, confirm: "Удалть статью?", method: :delete, class: 'btn btn-danger btn-xs'
= render 'comments/index'
- if user_signed_in?
  = render 'comments/form'